# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'helloworld' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Pods for helloworld
  pod 'Alamofire', '~> 5.0.0-rc.3'
  pod "PromiseKit", "~> 6.8"

  target 'helloworldTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'helloworldUITests' do
    # Pods for testing
  end

end
